server:
  port: 8001
spring:
  application:
    name: Cloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydev?useUnicode=true&character=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

# 开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:generator/*.xml


#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/    #注册到eureka的位置
  instance:
    instance-id: Cloud-provider-8001

info:
  app.name: springcloudDemo
  company.name: abchina
  author: zengchao

